services:
  - type: web
    name: dr-wessam-clinic
    env: node
    region: frankfurt
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: cd server && NODE_ENV=production node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
