// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clinic/Dashboard.tsx": () => import("../components/mockups/clinic/Dashboard.tsx"),
  "./components/mockups/clinic/Landing.tsx": () => import("../components/mockups/clinic/Landing.tsx"),
  "./components/mockups/clinic/Login.tsx": () => import("../components/mockups/clinic/Login.tsx"),
  "./components/mockups/clinic/Portal.tsx": () => import("../components/mockups/clinic/Portal.tsx")
};
