const mongoose = require('mongoose');

const siteSettingsSchema = new mongoose.Schema({
  key: { type: String, unique: true, required: true },
  doctorName: { type: String, default: 'د. وسام يوسف' },
  doctorTitle: { type: String, default: 'أخصائي تقويم الأسنان - بني مزار، المنيا' },
  doctorBio: { type: String, default: 'دكتور وسام يوسف أخصائي تقويم الأسنان في بني مزار، محافظة المنيا، مصر. خبرة أكثر من 10 سنوات في تقويم الأسنان للأطفال والبالغين.' },
  doctorExperience: { type: String, default: '+10 سنوات خبرة' },
  doctorPatients: { type: String, default: '+1000 مريض' },
  doctorSuccess: { type: String, default: '98% نسبة نجاح' },
  phone: { type: String, default: '01156798324' },
  whatsapp: { type: String, default: '201156798324' },
  address: { type: String, default: 'المنيا، بني مزار، شرق المحطة، ميدان 25 يناير، فوق مكتبة الأهرام' },
  googleMapsUrl: String,
  workingHours: { type: String, default: 'السبت - الخميس: 10 ص - 8 م' },
  heroTitle: { type: String, default: 'ابتسامة أجمل تبدأ من د. وسام يوسف' },
  heroSubtitle: { type: String, default: 'د. وسام يوسف أخصائي تقويم الأسنان في بني مزار، المنيا — خبرة +10 سنوات بأحدث التقنيات وأعلى معايير الجودة' },
  doctorUniversity: { type: String, default: '' },
  doctorGraduationYear: { type: String, default: '' },
  doctorEmail: { type: String, default: '' },
  doctorLanguages: { type: String, default: '' },
  certificates: [{ title: String, year: String, institution: String, imageUrl: String }],
  achievements: [{ title: String, description: String }],
  doctorTraining: [{ title: String, institution: String, year: String }],
  services: [{
    icon: String,
    title: String,
    description: String,
    isActive: { type: Boolean, default: true },
  }],
  reviews: [{
    name: String,
    rating: { type: Number, default: 5 },
    text: String,
    isActive: { type: Boolean, default: true },
  }],
  faqs: [{
    question: String,
    answer: String,
    isActive: { type: Boolean, default: true },
  }],
  instapayNumber: { type: String, default: '01156798324' },
  seoTitle: String,
  seoDescription: String,
  seoKeywords: String,
  systemName: { type: String, default: 'نظام عيادة د. وسام يوسف' },
  systemSubtitle: { type: String, default: 'نظام إدارة العيادة المتكامل' },
  portalWelcomeTitle: { type: String, default: 'أهلاً بك في بوابتك الطبية' },
  portalWelcomeMsg: { type: String, default: 'تابع مواعيدك وجلساتك ومدفوعاتك بكل سهولة' },
  bookingWhatsappMsg: { type: String, default: 'مرحباً دكتور، أريد حجز موعد' },
  appointmentLocation: { type: String, default: 'بني مزار - المنيا - شرق المحطة فوق مكتبة الأهرام' },
  clinicTagline: { type: String, default: 'ابتسامة أجمل تبدأ من هنا' },
  loginWelcomeMsg: { type: String, default: 'سجل دخولك للوصول إلى حسابك' },
}, { timestamps: true });

module.exports = mongoose.model('SiteSettings', siteSettingsSchema);
